// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgmxkthaxdrqzjcfhpnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnbXhrdGhheGRycXpqY2ZocG5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzA3OTYsImV4cCI6MjA2OTc0Njc5Nn0.m9YM8pc_Ng3Zir6AdlrQasAN2bzezab7fZ3ltzaMMmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});